version: '3.8'

services:
  db:
    image: cgr.dev/chainguard/postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    networks:
      - mynetwork

  fastapi:
    build: .
    environment:
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_NAME=${DB_NAME}

    ports: 
      - 8000:8000
    depends_on:
      - db
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
