version: '3.8'

services:

  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - db
    networks:
      -  mynetwork
    environment:
      SONAR_JDBC_URL: jdbc:postgresql:db:5432/sonar
      SONAR_JDBC_USERNAME: ${SONAR_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_PASSWORD}
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs

      
  db:
    image: cgr.dev/chainguard/postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    networks:
      - mynetwork

  fastapi:
    build: .
    environment:
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_HOST=  db
    - DB_PORT=${DB_PORT}
    - DB_NAME=${DB_NAME}

    ports: 
      - 8000:8000
    depends_on:
      - db
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
  sonar_data:
  sonar_logs: