name: API

on:
  push:
    branches: [main]

jobs:
  API:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3

     - name: Docker Login
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.USER }}
         password: ${{ secrets.PASSWORD }}

     - name: Build and push Docker images
       uses: docker/build-push-action@v4
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: |
           lenepires19/web:v1
           lenepires19/web:latest
