name: API

on:
  push:
    branches: [main]

jobs:
  API:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
       
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2 
      
     - name: Docker Login
       uses: docker/login-action@v3
       with:
           username: ${{ secrets.USER }}
           password: ${{ secrets.PASSWORD }}
           
     - name: Build and push Docker images
       uses: docker/build-push-action@v4
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: |
            lenepires19/web:latest

     - name: Aqua Security Trivy Scan
       uses: aquasecurity/trivy-action@0.25.0
       with:
         image-ref: lenepires19/web:latest
         severity: LOW,MEDIUM,HIGH,CRITICAL 
         format: table  
         exit-code: 1
                   
                   
           
   
