name: API

on:
  push:
    branches: [main]

jobs:
  API:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
       
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2 
      
     - name: Docker Login
       uses: docker/login-action@v3
       with:
           username: ${{ secrets.USER }}
           password: ${{ secrets.PASSWORD }}
           
     - name: Build and push Docker images
       uses: docker/build-push-action@v4
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: |
            lenepires19/web:latest
            lenepires19/web:v${{ github.run_number }}
  scan:
    runs-on: ubuntu-latest
     
    steps:
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.USER }}/web:v${{ github.run_number }}
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          ignore-unfixed: 'true' 
